default: &default
  adapter: <%= ENV["DATABASE_ADAPTER"]  || "postgresql" %>
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 6) %>

development:
  <<: *default
  database: document_holder_development

test:
  <<: *default
  database: document_holder_test